version: 0.2

phases:

	install:
		runtime-versions:
                 java: correct11
        build:
		commands:
		 - echo Build started on 'date'
                 - mvn package
	post_build
	        commands:
                   -echo build completed on 'date'
 artifacts:
	files:
          -target/=.jar
         discard-paths: yes


